// <auto-generated />
using System;
using GestionSalleEmit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionSalleEmit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523115831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionSalleEmit.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEDT"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("int");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("int");

                    b.Property<int>("IdSalle")
                        .HasColumnType("int");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEDT");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdNiveau");

                    b.HasIndex("IdSalle");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("EmailEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnseignant");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseigner", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("int");

                    b.HasKey("IdEnseignant", "IdMatiere");

                    b.HasIndex("IdMatiere");

                    b.ToTable("Enseigners");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Filiere", b =>
                {
                    b.Property<int>("IdFiliere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiliere"));

                    b.Property<string>("NomFiliere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdFiliere");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatiere"));

                    b.Property<int>("Coefficient")
                        .HasColumnType("int");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("int");

                    b.HasKey("IdMatiere");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNiveau"));

                    b.Property<int?>("FiliereIdFiliere")
                        .HasColumnType("int");

                    b.Property<int>("IdParcours")
                        .HasColumnType("int");

                    b.Property<string>("NomNiveau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNiveau");

                    b.HasIndex("FiliereIdFiliere");

                    b.HasIndex("IdParcours");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Parcours", b =>
                {
                    b.Property<int>("IdParcours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParcours"));

                    b.Property<int>("IdFiliere")
                        .HasColumnType("int");

                    b.Property<string>("NomParcours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdParcours");

                    b.HasIndex("IdFiliere");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeSalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("GestionSalleEmit.Models.Enseignant", "Enseignant")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Matiere", "Matiere")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Niveau", "Niveau")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Niveau");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseigner", b =>
                {
                    b.HasOne("GestionSalleEmit.Models.Enseignant", "Enseignant")
                        .WithMany("Enseigners")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Matiere", "Matiere")
                        .WithMany("Enseigners")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Niveau", b =>
                {
                    b.HasOne("GestionSalleEmit.Models.Filiere", null)
                        .WithMany("Niveaux")
                        .HasForeignKey("FiliereIdFiliere");

                    b.HasOne("GestionSalleEmit.Models.Parcours", "Parcours")
                        .WithMany("Niveaux")
                        .HasForeignKey("IdParcours")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Parcours", b =>
                {
                    b.HasOne("GestionSalleEmit.Models.Filiere", "Filiere")
                        .WithMany("Parcours")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseignant", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Enseigners");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Filiere", b =>
                {
                    b.Navigation("Niveaux");

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Matiere", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Enseigners");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Niveau", b =>
                {
                    b.Navigation("EmploisDuTemps");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Parcours", b =>
                {
                    b.Navigation("Niveaux");
                });
#pragma warning restore 612, 618
        }
    }
}
