// <auto-generated />
using System;
using GestionSalleEmit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionSalleEmit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionSalleEmit.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEDT"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("int");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("int");

                    b.Property<int>("IdSalle")
                        .HasColumnType("int");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEDT");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdNiveau");

                    b.HasIndex("IdSalle");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("EmailEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomEnseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnseignant");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseigner", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("int");

                    b.HasKey("IdEnseignant", "IdMatiere");

                    b.HasIndex("IdMatiere");

                    b.ToTable("Enseigners");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Filiere", b =>
                {
                    b.Property<int>("IdFiliere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiliere"));

                    b.Property<string>("NomFiliere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFiliere");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("int");

                    b.HasKey("IdMatiere");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNiveau"));

                    b.Property<int>("IdFiliere")
                        .HasColumnType("int");

                    b.Property<string>("NomNiveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNiveau");

                    b.HasIndex("IdFiliere");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSalle"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeSalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("GestionSalleEmit.Models.Enseignant", "Enseignant")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Matiere", "Matiere")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Niveau", "Niveau")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Niveau");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseigner", b =>
                {
                    b.HasOne("GestionSalleEmit.Models.Enseignant", "Enseignant")
                        .WithMany("Enseigners")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSalleEmit.Models.Matiere", "Matiere")
                        .WithMany("Enseigners")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Niveau", b =>
                {
                    b.HasOne("GestionSalleEmit.Models.Filiere", "Filiere")
                        .WithMany("Niveaux")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Enseignant", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Enseigners");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Filiere", b =>
                {
                    b.Navigation("Niveaux");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Matiere", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Enseigners");
                });

            modelBuilder.Entity("GestionSalleEmit.Models.Niveau", b =>
                {
                    b.Navigation("EmploisDuTemps");
                });
#pragma warning restore 612, 618
        }
    }
}
